# -*- mode: ruby -*-

Vagrant.configure("2") do |config|

  # Managed Node
  ##############

  # CentOS 7.4
  config.vm.define "server1" do |node|
    node.vm.box = "bento/centos-7.4"
    node.vm.network "private_network", ip: "192.168.10.11"
    node.vm.provider "virtualbox" do |v|
      v.linked_clone = true
      v.memory = 512
    end
    node.vm.provision "shell", inline: "yum install -y openssh-server python"
  end

  # CentOS 7.4
  config.vm.define "server2" do |node|
    node.vm.box = "bento/centos-7.4"
    node.vm.network "private_network", ip: "192.168.10.12"
    node.vm.provider "virtualbox" do |v|
      v.linked_clone = true
      v.memory = 512
    end
    node.vm.provision "shell", inline: "yum install -y openssh-server python"
  end

  # Control Machine
  #################

  # Ubuntu 16.04
  config.vm.define "workstation", primary: true do |node|
    node.vm.box = "ubuntu/xenial64"
    node.vm.provider "virtualbox" do |v|
      v.linked_clone = true
      v.memory = 1024
    end

    # 更換 apt 鏡像站。
    node.vm.provision "shell",
      inline: "sed -i 's/archive.ubuntu.com/free.nchc.org.tw/g' /etc/apt/sources.list"

    # 安裝 add-apt-repository 必要套件。
    node.vm.provision "shell",
      inline: "apt update && \
                apt install -y python-software-properties software-properties-common"

    # 使用 Ansible 官方的 PPA 套件來源。
    node.vm.provision "shell",
      inline: "add-apt-repository -y ppa:ansible/ansible && apt update"

    # 安裝 Ansible。
    node.vm.provision "shell",
      inline: "apt install -y ansible"
  end

end

# vi: set ft=ruby :
