---

- name: Say 'hello world'
  hosts: localhost
  tasks:

    - name: Echo 'hello world'
      command: echo 'hello world'
      register: result

    - name: Print stdout
      debug:
        msg: "{{ result.stdout }}"

# vim: ft=yaml.ansible :
