---

- name: 說「哈囉世界」
  hosts: localhost
  tasks:

    - name: 印出「哈囉世界」
      command: echo '哈囉世界'
      register: result

    - name: 印出標準輸出訊息
      debug:
        msg: "{{ result.stdout }}"

# vim: ft=yaml.ansible :
